
const KEYS={areas:'cr_areas_v1',logs:'cr_logs_v1',settings:'cr_settings_v1',run:'cr_run_v1'};
let areas=[], logs=[], settings={name:'Coordinación',role:'admin'}, selectedFloor=null, selectedStatus='';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const nowDate=()=>new Date().toISOString().slice(0,10); const nowTime=()=>new Date().toTimeString().slice(0,5);
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function save(){localStorage.setItem(KEYS.areas,JSON.stringify(areas));localStorage.setItem(KEYS.logs,JSON.stringify(logs));localStorage.setItem(KEYS.settings,JSON.stringify(settings));}
async function init(){
  const stored=localStorage.getItem(KEYS.areas); areas=stored?JSON.parse(stored):await fetch('areas.json').then(r=>r.json());
  logs=JSON.parse(localStorage.getItem(KEYS.logs)||'[]'); settings=JSON.parse(localStorage.getItem(KEYS.settings)||JSON.stringify(settings));
  $('#todayLabel').textContent=new Intl.DateTimeFormat('es-CR',{dateStyle:'long'}).format(new Date());
  $('#currentUser').textContent=settings.name; $('#userName').value=settings.name; $('#userRole').value=settings.role; applyRole(); renderFloors(); bind();
}
function applyRole(){ $$('.admin-only').forEach(x=>x.classList.toggle('hidden',settings.role!=='admin')); }
function bind(){
 $('#menuBtn').onclick=()=>$('#nav').classList.toggle('hidden'); $$('.nav-link').forEach(b=>b.onclick=()=>showView(b.dataset.view));
 $('#backFloors').onclick=()=>{selectedFloor=null;$('#floorDetail').classList.add('hidden');$('#floorGrid').classList.remove('hidden')};
 $('#resetDayBtn').onclick=()=>{localStorage.setItem(KEYS.run,uid()); toast('Nuevo recorrido iniciado')};
 $('#saveStatus').onclick=saveStatus; $$('.status-btn').forEach(b=>b.onclick=()=>{$$('.status-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedStatus=b.dataset.status});
 $('#exportCsv').onclick=exportCsv; $('#applyFilters').onclick=renderReports; $('#addAreaBtn').onclick=()=>openAreaEditor();
 $('#saveArea').onclick=saveArea; $('#areaFloorFilter').onchange=renderAreasAdmin; $('#areaSearch').oninput=renderAreasAdmin;
 $('#saveSettings').onclick=()=>{settings={name:$('#userName').value.trim()||'Usuario',role:$('#userRole').value};save();$('#currentUser').textContent=settings.name;applyRole();toast('Configuración guardada')};
}
function showView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+name+'View').classList.remove('hidden');$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#nav').classList.add('hidden');if(name==='pending')renderPending();if(name==='reports')renderReports();if(name==='areas')renderAreasAdmin();}
function latestFor(areaId){return [...logs].reverse().find(l=>l.areaId===areaId&&l.date===nowDate())}
function renderFloors(){
 $('#floorGrid').innerHTML=[1,2,3,4].map(f=>{let a=areas.filter(x=>x.floor===f&&x.active),done=a.filter(x=>latestFor(x.id)?.status==='Limpio').length,p=a.length?Math.round(done/a.length*100):0;return `<article class="floor-card card" onclick="openFloor(${f})"><div class="floor-top"><span class="floor-number">Piso ${f}</span><span class="floor-count">${done} / ${a.length}</span></div><div class="progress"><span style="width:${p}%"></span></div><span class="area-meta">${p}% completado</span></article>`}).join('');
}
window.openFloor=function(f){selectedFloor=f;$('#floorGrid').classList.add('hidden');$('#floorDetail').classList.remove('hidden');$('#floorEyebrow').textContent='RECORRIDO';$('#floorTitle').textContent='Piso '+f;renderAreaList()}
function statusClass(s){return {'Limpio':'s-clean','Área ocupada':'s-occupied','Reprogramado':'s-rescheduled','Requiere atención':'s-attention'}[s]||'s-pending'}
function renderAreaList(){let arr=areas.filter(x=>x.floor===selectedFloor&&x.active).sort((a,b)=>a.order-b.order);$('#areaList').innerHTML=arr.map(a=>{let l=latestFor(a.id),s=l?.status||'Pendiente';return `<article class="area-card card"><div><p class="eyebrow">${a.code}</p><h3>${a.name}</h3><span class="area-meta">${a.type}${l?.note?' · '+escapeHtml(l.note):''}</span></div><button class="state-pill ${statusClass(s)}" onclick="openStatus('${a.id}')">${s}</button></article>`}).join('')||'<div class="card area-card">No hay áreas activas.</div>';renderFloors()}
window.openStatus=function(id){let a=areas.find(x=>x.id===id),l=latestFor(id);$('#statusAreaId').value=id;$('#statusAreaCode').textContent=a.code;$('#statusAreaName').textContent=a.name;$('#statusNote').value=l?.note||'';$('#rescheduleTime').value=l?.rescheduleTime||'';selectedStatus=l?.status||'';$$('.status-btn').forEach(b=>b.classList.toggle('selected',b.dataset.status===selectedStatus));$('#statusDialog').showModal()}
function saveStatus(){let id=$('#statusAreaId').value;if(!selectedStatus)return toast('Seleccione un estado');let a=areas.find(x=>x.id===id);logs.push({id:uid(),areaId:id,areaName:a.name,floor:a.floor,date:nowDate(),time:nowTime(),status:selectedStatus,note:$('#statusNote').value.trim(),rescheduleTime:$('#rescheduleTime').value,user:settings.name,runId:localStorage.getItem(KEYS.run)||'default'});save();$('#statusDialog').close();renderAreaList();toast('Estado guardado')}
function renderPending(){let items=areas.map(a=>({a,l:latestFor(a.id)})).filter(x=>x.l&&x.l.status!=='Limpio');$('#pendingList').innerHTML=items.map(({a,l})=>`<article class="area-card card"><div><p class="eyebrow">PISO ${a.floor} · ${a.code}</p><h3>${a.name}</h3><span class="area-meta">${escapeHtml(l.note||'Sin observación')}${l.rescheduleTime?' · Retomar '+l.rescheduleTime:''}</span></div><button class="state-pill ${statusClass(l.status)}" onclick="openStatus('${a.id}')">${l.status}</button></article>`).join('')||'<div class="card area-card">No hay pendientes registrados hoy.</div>'}
function filteredLogs(){let from=$('#dateFrom').value,to=$('#dateTo').value,f=$('#reportFloor').value;return logs.filter(l=>(!from||l.date>=from)&&(!to||l.date<=to)&&(!f||String(l.floor)===f)).slice().reverse()}
function renderReports(){let rows=filteredLogs(),clean=rows.filter(x=>x.status==='Limpio').length,occ=rows.filter(x=>x.status==='Área ocupada').length,pend=rows.filter(x=>x.status!=='Limpio').length,rate=rows.length?Math.round(clean/rows.length*100):0;$('#kpis').innerHTML=[['Cumplimiento',rate+'%'],['Registros',rows.length],['Limpios',clean],['Pendientes',pend]].map(x=>`<div class="kpi card"><span class="label">${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#reportBody').innerHTML=rows.map(l=>`<tr><td>${l.date}</td><td>${l.time}</td><td>${l.floor}</td><td>${escapeHtml(l.areaName)}</td><td><span class="state-pill ${statusClass(l.status)}">${l.status}</span></td><td>${escapeHtml(l.user)}</td><td>${escapeHtml(l.note||'')}</td></tr>`).join('')}
function exportCsv(){let rows=filteredLogs(),data=[['Fecha','Hora','Piso','Área','Estado','Responsable','Observación','Reprogramado para'],...rows.map(l=>[l.date,l.time,l.floor,l.areaName,l.status,l.user,l.note||'',l.rescheduleTime||''])];let csv='\ufeff'+data.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='reporte_recorridos_'+nowDate()+'.csv';a.click();URL.revokeObjectURL(a.href)}
function renderAreasAdmin(){let f=$('#areaFloorFilter').value,q=$('#areaSearch').value.toLowerCase();let arr=areas.filter(a=>(!f||String(a.floor)===f)&&(!q||[a.name,a.code,a.type].join(' ').toLowerCase().includes(q))).sort((a,b)=>a.floor-b.floor||a.order-b.order);$('#areasBody').innerHTML=arr.map(a=>`<tr><td>${a.order}</td><td>${a.floor}</td><td>${escapeHtml(a.name)}</td><td>${a.code}</td><td>${escapeHtml(a.type)}</td><td>${a.active?'Activa':'Inactiva'}</td><td><div class="actions"><button class="action-btn" onclick="openAreaEditor('${a.id}')">Editar</button><button class="action-btn" onclick="deleteArea('${a.id}')">Eliminar</button></div></td></tr>`).join('')}
window.openAreaEditor=function(id){let a=id?areas.find(x=>x.id===id):null;$('#areaDialogTitle').textContent=a?'Editar área':'Agregar área';$('#editAreaId').value=a?.id||'';$('#editFloor').value=a?.floor||1;$('#editOrder').value=a?.order||(areas.filter(x=>x.floor===1).length+1);$('#editName').value=a?.name||'';$('#editCode').value=a?.code||'';$('#editType').value=a?.type||'';$('#editNotes').value=a?.notes||'';$('#editActive').checked=a?.active??true;$('#areaDialog').showModal()}
function saveArea(){let oldId=$('#editAreaId').value,obj={id:oldId||uid(),floor:+$('#editFloor').value,order:+$('#editOrder').value,name:$('#editName').value.trim(),code:$('#editCode').value.trim(),type:$('#editType').value.trim(),notes:$('#editNotes').value.trim(),active:$('#editActive').checked};if(!obj.name||!obj.code||!obj.type)return toast('Complete los datos requeridos');if(areas.some(x=>x.code.toLowerCase()===obj.code.toLowerCase()&&x.id!==oldId))return toast('El código ya existe');if(oldId)areas[areas.findIndex(x=>x.id===oldId)]=obj;else areas.push(obj);save();$('#areaDialog').close();renderAreasAdmin();renderFloors();toast('Área guardada')}
window.deleteArea=function(id){let hasHistory=logs.some(l=>l.areaId===id),a=areas.find(x=>x.id===id);if(hasHistory){a.active=false;save();renderAreasAdmin();renderFloors();return toast('El área tiene historial y fue desactivada');}if(confirm('¿Eliminar esta área?')){areas=areas.filter(x=>x.id!==id);save();renderAreasAdmin();renderFloors();toast('Área eliminada')}}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
init();
